export interface Job {
  id: number;
  title: string;
  company: string;
  companyColor: string;
  companyInitials: string;
  location: string;
  province: string;
  type: string;
  category: string;
  salary: string;
  experience: string;
  posted: string;
  deadline: string;
  urgent: boolean;
  featured: boolean;
  views: number;
  applicants: number;
  description: string;
  requirements: string[];
  skills: string[];
  logo: string;
  image: string;
}

export const jobs: Job[] = [
  // ── HOTELS ───────────────────────────────────────────────────────────────
  {
    id: 1,
    title: "Executive Chef",
    company: "Kigali Serena Hotel",
    companyColor: "#1565C0",
    companyInitials: "KSH",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 800,000 – 1,200,000 /mo",
    experience: "5+ years",
    posted: "2 days ago",
    deadline: "May 30, 2026",
    urgent: true,
    featured: true,
    views: 1842,
    applicants: 63,
    description:
      "Lead the culinary team at one of Kigali's premier luxury hotels. Oversee kitchen operations, menu creation, and ensure exceptional dining experiences across all F&B outlets including the main restaurant, pool bar, and banqueting facilities.",
    requirements: [
      "Culinary degree or equivalent professional qualification",
      "5+ years in a senior kitchen role, luxury hotel preferred",
      "Proven experience with international cuisine and menu engineering",
      "Strong leadership, team management and cost-control skills",
      "HACCP and food safety certification",
    ],
    skills: ["Menu Engineering", "HACCP", "Team Leadership", "International Cuisine", "Cost Control"],
    logo: "🏨",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=350&fit=crop",
  },
  {
    id: 2,
    title: "Front Desk Manager",
    company: "Gorilla's Nest Lodge",
    companyColor: "#2E7D32",
    companyInitials: "GNL",
    location: "Kinigi, Musanze",
    province: "Northern",
    type: "Full-time",
    category: "Lodge",
    salary: "RWF 450,000 – 600,000 /mo",
    experience: "3+ years",
    posted: "1 week ago",
    deadline: "May 20, 2026",
    urgent: false,
    featured: false,
    views: 974,
    applicants: 38,
    description:
      "Manage front office operations for an eco-luxury lodge near Volcanoes National Park. Supervise guest check-in/out, reservations, and concierge services for an international guest base.",
    requirements: [
      "Hospitality management degree",
      "Fluent in English and French; Kinyarwanda a plus",
      "Experience with Opera or similar PMS software",
      "Excellent customer service and problem-solving skills",
    ],
    skills: ["Opera PMS", "Guest Relations", "French", "Revenue Management", "Concierge"],
    logo: "🌿",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&h=350&fit=crop",
  },
  {
    id: 3,
    title: "Head Bartender",
    company: "Sky Bar Kigali",
    companyColor: "#6A1B9A",
    companyInitials: "SBK",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Bar",
    salary: "RWF 350,000 – 500,000 /mo",
    experience: "3+ years",
    posted: "3 days ago",
    deadline: "May 10, 2026",
    urgent: true,
    featured: true,
    views: 2104,
    applicants: 91,
    description:
      "Create and manage cocktail menus for Kigali's most iconic rooftop bar. Train junior staff and ensure top-tier beverage service standards while maintaining high energy in a vibrant environment.",
    requirements: [
      "Advanced bartending certification (WSET or equivalent)",
      "Creative mixology skills and passion for craft cocktails",
      "Knowledge of wines, spirits, and craft beer",
      "Evening and weekend availability required",
    ],
    skills: ["Mixology", "Cocktail Design", "WSET", "Team Training", "Bar Management"],
    logo: "🍸",
    image: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=600&h=350&fit=crop",
  },
  {
    id: 4,
    title: "Restaurant Manager",
    company: "Repub Lounge",
    companyColor: "#BF360C",
    companyInitials: "RL",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Restaurant",
    salary: "RWF 500,000 – 700,000 /mo",
    experience: "4+ years",
    posted: "5 days ago",
    deadline: "May 25, 2026",
    urgent: false,
    featured: false,
    views: 1203,
    applicants: 47,
    description:
      "Oversee daily restaurant operations, manage staff scheduling, ensure quality standards, and drive revenue growth for one of Kigali's most beloved dining spots — known for its eclectic menu and vibrant atmosphere.",
    requirements: [
      "Restaurant management experience (4+ years)",
      "Financial acumen and experience managing budgets",
      "Team leadership and conflict resolution skills",
      "Food safety certification (minimum Level 2)",
    ],
    skills: ["Restaurant Operations", "P&L Management", "Staff Scheduling", "Food Safety", "Guest Experience"],
    logo: "🍽️",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=350&fit=crop",
  },
  {
    id: 5,
    title: "Guest Relations Officer",
    company: "One&Only Nyungwe House",
    companyColor: "#00695C",
    companyInitials: "ONH",
    location: "Nyamasheke, Western Province",
    province: "Western",
    type: "Full-time",
    category: "Lodge",
    salary: "RWF 380,000 – 520,000 /mo",
    experience: "2+ years",
    posted: "1 day ago",
    deadline: "May 15, 2026",
    urgent: false,
    featured: false,
    views: 688,
    applicants: 22,
    description:
      "Deliver world-class guest experiences at an ultra-luxury lodge on the edge of Nyungwe Forest. Coordinate activities, transfers, and personalized itineraries for high-profile international guests.",
    requirements: [
      "Hospitality background with luxury property experience",
      "Excellent communication and interpersonal skills",
      "Multi-lingual: English + French preferred; Kinyarwanda an asset",
      "Passion for eco-tourism and conservation",
    ],
    skills: ["Luxury Service", "French", "Itinerary Planning", "Eco-Tourism", "VIP Hosting"],
    logo: "🌲",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&h=350&fit=crop",
  },
  {
    id: 6,
    title: "Housekeeping Supervisor",
    company: "Marriott Hotel Kigali",
    companyColor: "#C62828",
    companyInitials: "MHK",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 320,000 – 420,000 /mo",
    experience: "2+ years",
    posted: "2 weeks ago",
    deadline: "Jun 5, 2026",
    urgent: false,
    featured: false,
    views: 812,
    applicants: 54,
    description:
      "Supervise the housekeeping team to maintain Marriott brand standards across all rooms and public areas. Schedule staff, conduct inspections, manage linen inventory, and maintain departmental hygiene logs.",
    requirements: [
      "Housekeeping or hospitality diploma",
      "Minimum 2 years supervisory experience",
      "Strong attention to detail and quality standards",
      "Physical stamina for full-shift inspections",
    ],
    skills: ["Room Inspection", "Team Supervision", "Inventory Control", "Brand Standards", "Scheduling"],
    logo: "🏩",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&h=350&fit=crop",
  },
  {
    id: 7,
    title: "Sous Chef",
    company: "Heaven Restaurant & Boutique Hotel",
    companyColor: "#E65100",
    companyInitials: "HRB",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Restaurant",
    salary: "RWF 480,000 – 650,000 /mo",
    experience: "3+ years",
    posted: "4 days ago",
    deadline: "May 12, 2026",
    urgent: true,
    featured: true,
    views: 1540,
    applicants: 78,
    description:
      "Support the Executive Chef in running the kitchen of a celebrated Kigali institution. Focus on Rwandan and fusion cuisine, staff training, and efficient prep management for both à la carte and private events.",
    requirements: [
      "Culinary school training required",
      "Proficiency in African and international cuisines",
      "Team player with demonstrated leadership potential",
      "HACCP knowledge and kitchen hygiene certification",
    ],
    skills: ["Rwandan Cuisine", "Fusion Cooking", "HACCP", "Prep Management", "Staff Training"],
    logo: "👨‍🍳",
    image: "https://images.unsplash.com/photo-1581349485608-9469926a8e5e?w=600&h=350&fit=crop",
  },
  {
    id: 8,
    title: "Barista & Coffee Specialist",
    company: "Bourbon Coffee",
    companyColor: "#5D4037",
    companyInitials: "BC",
    location: "Multiple Locations, Kigali",
    province: "Kigali",
    type: "Full-time",
    category: "Bar",
    salary: "RWF 200,000 – 320,000 /mo",
    experience: "1+ year",
    posted: "1 week ago",
    deadline: "May 28, 2026",
    urgent: false,
    featured: false,
    views: 2631,
    applicants: 143,
    description:
      "Prepare exceptional Rwandan specialty coffee and educate customers on Rwanda's rich coffee heritage. Ideal for passionate baristas who love the story behind the cup and enjoy creating memorable café moments.",
    requirements: [
      "Barista certification preferred (SCA or equivalent)",
      "Knowledge of single-origin coffee and brewing methods",
      "Strong customer-facing experience and warm personality",
      "Positive, energetic attitude",
    ],
    skills: ["Espresso", "Latte Art", "SCA Certified", "Customer Service", "Coffee Origins"],
    logo: "☕",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=350&fit=crop",
  },
  {
    id: 9,
    title: "Events Coordinator",
    company: "Kigali Convention Centre",
    companyColor: "#283593",
    companyInitials: "KCC",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Lounge",
    salary: "RWF 420,000 – 580,000 /mo",
    experience: "3+ years",
    posted: "6 days ago",
    deadline: "May 22, 2026",
    urgent: false,
    featured: false,
    views: 1187,
    applicants: 59,
    description:
      "Plan and execute corporate events, conferences, and banquets at Rwanda's premier convention centre. Liaise with clients, vendors and AV teams to deliver world-class event experiences.",
    requirements: [
      "Event management degree or diploma",
      "Strong project management and multitasking skills",
      "Vendor negotiation and relationship management experience",
      "Bilingual English/French required",
    ],
    skills: ["Event Planning", "MICE", "Vendor Management", "French", "AV Coordination"],
    logo: "🎪",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&h=350&fit=crop",
  },
  {
    id: 10,
    title: "Hotel General Manager",
    company: "Radisson Blu Kigali",
    companyColor: "#1A237E",
    companyInitials: "RBK",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 2,000,000 – 3,500,000 /mo",
    experience: "10+ years",
    posted: "3 days ago",
    deadline: "Jun 15, 2026",
    urgent: true,
    featured: true,
    views: 3412,
    applicants: 27,
    description:
      "Lead all aspects of hotel operations at the newly expanded Radisson Blu Kigali. Full P&L accountability, talent development, and representing the brand at the highest level with government and corporate stakeholders.",
    requirements: [
      "Hotel management degree (minimum Bachelor's)",
      "10+ years of progressive luxury hotel experience",
      "Proven P&L management and owner relations skills",
      "International hotel brand standard knowledge",
    ],
    skills: ["P&L Management", "Hotel Operations", "Brand Standards", "Stakeholder Relations", "Revenue Growth"],
    logo: "🏦",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&h=350&fit=crop",
  },
  {
    id: 11,
    title: "Pastry Chef",
    company: "Kigali Marriott Hotel",
    companyColor: "#C62828",
    companyInitials: "KMH",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 550,000 – 750,000 /mo",
    experience: "4+ years",
    posted: "5 days ago",
    deadline: "May 18, 2026",
    urgent: false,
    featured: false,
    views: 921,
    applicants: 41,
    description:
      "Design and execute the pastry and bakery menu for all F&B outlets at the Marriott. Create showpiece desserts for events, manage pastry inventory, and ensure consistency in quality and presentation across all services.",
    requirements: [
      "Pastry arts degree or equivalent culinary training",
      "Advanced chocolate and sugar work skills",
      "Experience in a luxury hotel pastry kitchen",
      "High creativity and attention to presentation detail",
    ],
    skills: ["Patisserie", "Chocolate Work", "Sugar Craft", "Plating", "Menu Design"],
    logo: "🧁",
    image: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600&h=350&fit=crop",
  },
  {
    id: 12,
    title: "Spa & Wellness Manager",
    company: "Lake Kivu Serena Hotel",
    companyColor: "#00838F",
    companyInitials: "LKS",
    location: "Gisenyi, Western Province",
    province: "Western",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 600,000 – 850,000 /mo",
    experience: "4+ years",
    posted: "1 week ago",
    deadline: "Jun 1, 2026",
    urgent: false,
    featured: false,
    views: 743,
    applicants: 29,
    description:
      "Oversee the spa, fitness centre and wellness programmes at this lakeside luxury retreat. Manage therapists, develop treatment menus, drive spa revenue, and maintain internationally certified standards.",
    requirements: [
      "Spa management certification (ISPA or equivalent)",
      "Deep knowledge of wellness therapies and treatments",
      "Team leadership and scheduling experience",
      "Revenue management and retail sales skills",
    ],
    skills: ["Spa Management", "Wellness Therapies", "Revenue Management", "Team Leadership", "Retail Sales"],
    logo: "💆",
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&h=350&fit=crop",
  },
  {
    id: 13,
    title: "Food & Beverage Director",
    company: "Kigali Heights Hotel",
    companyColor: "#37474F",
    companyInitials: "KHH",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 1,200,000 – 1,800,000 /mo",
    experience: "7+ years",
    posted: "2 days ago",
    deadline: "May 14, 2026",
    urgent: true,
    featured: false,
    views: 2089,
    applicants: 34,
    description:
      "Direct all F&B operations across multiple outlets including restaurants, bars, room service and banqueting. Drive profit, champion menu innovation and consistently achieve high guest satisfaction scores.",
    requirements: [
      "F&B Director level experience in a hotel environment",
      "Strong financial management and forecasting skills",
      "Menu engineering and cost-of-sales expertise",
      "Multi-outlet management of 5+ F&B venues",
    ],
    skills: ["F&B Operations", "Menu Engineering", "Profit Management", "HACCP", "Multi-Outlet"],
    logo: "🍷",
    image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=600&h=350&fit=crop",
  },
  {
    id: 14,
    title: "Sommelier",
    company: "The Manor Hotel Kigali",
    companyColor: "#4A148C",
    companyInitials: "TMK",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Restaurant",
    salary: "RWF 480,000 – 650,000 /mo",
    experience: "3+ years",
    posted: "4 days ago",
    deadline: "May 29, 2026",
    urgent: false,
    featured: false,
    views: 654,
    applicants: 18,
    description:
      "Curate and manage an exceptional wine cellar and beverage programme at one of Kigali's upscale dining venues. Lead wine pairing dinners, staff training sessions, and develop exclusive wine tasting events.",
    requirements: [
      "WSET Level 3 or Court of Master Sommeliers certification",
      "Extensive knowledge of Old and New World wines",
      "Training and presentation skills for staff and guests",
      "Genuine passion for fine dining hospitality",
    ],
    skills: ["WSET Level 3", "Wine Pairing", "Cellar Management", "Staff Training", "Beverage Cost"],
    logo: "🍾",
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&h=350&fit=crop",
  },
  {
    id: 15,
    title: "Lodge Guide & Safari Coordinator",
    company: "Sabyinyo Silverback Lodge",
    companyColor: "#33691E",
    companyInitials: "SSL",
    location: "Musanze, Northern Province",
    province: "Northern",
    type: "Full-time",
    category: "Lodge",
    salary: "RWF 350,000 – 500,000 /mo",
    experience: "2+ years",
    posted: "3 days ago",
    deadline: "May 17, 2026",
    urgent: false,
    featured: false,
    views: 1320,
    applicants: 55,
    description:
      "Lead gorilla trekking excursions, nature walks and cultural tours for guests at this award-winning lodge. Ensure safety, provide in-depth expertise on Rwanda's biodiversity and create unforgettable wildlife experiences.",
    requirements: [
      "RDB-certified nature guide licence",
      "Deep knowledge of Rwandan flora, fauna and conservation",
      "First aid and wilderness safety certification",
      "Fluent English; French a strong advantage",
    ],
    skills: ["Gorilla Trekking", "RDB Certified", "First Aid", "Conservation", "Guest Storytelling"],
    logo: "🦍",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600&h=350&fit=crop",
  },
  {
    id: 16,
    title: "Reservations & Revenue Manager",
    company: "Bisate Lodge",
    companyColor: "#1B5E20",
    companyInitials: "BL",
    location: "Kinigi, Musanze",
    province: "Northern",
    type: "Full-time",
    category: "Lodge",
    salary: "RWF 550,000 – 750,000 /mo",
    experience: "3+ years",
    posted: "6 days ago",
    deadline: "Jun 10, 2026",
    urgent: false,
    featured: false,
    views: 877,
    applicants: 31,
    description:
      "Manage all booking channels, pricing strategy, and occupancy optimisation for this high-end eco-lodge. Interface with global tour operators, OTAs, and develop corporate rate agreements.",
    requirements: [
      "Revenue management experience in hospitality",
      "Knowledge of channel management and OTA systems",
      "Strong analytical and Excel/data skills",
      "Eco-luxury hospitality background preferred",
    ],
    skills: ["Revenue Management", "OTA Management", "Rate Strategy", "Booking Systems", "Analytics"],
    logo: "📊",
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764bef?w=600&h=350&fit=crop",
  },
  {
    id: 17,
    title: "Night Auditor",
    company: "Park Inn by Radisson",
    companyColor: "#0D47A1",
    companyInitials: "PIR",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 250,000 – 340,000 /mo",
    experience: "1+ year",
    posted: "2 weeks ago",
    deadline: "May 20, 2026",
    urgent: false,
    featured: false,
    views: 590,
    applicants: 44,
    description:
      "Manage overnight front desk operations and reconcile daily financial transactions. Assist late-arriving guests and prepare morning management reports for review by department heads.",
    requirements: [
      "Accounting or hospitality background",
      "Proficiency with Opera PMS or similar systems",
      "Night shift availability (10pm–7am)",
      "High attention to detail and numerical accuracy",
    ],
    skills: ["Opera PMS", "Night Audit", "Financial Reconciliation", "Guest Service", "Reporting"],
    logo: "🌙",
    image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600&h=350&fit=crop",
  },
  {
    id: 18,
    title: "Senior Waiter / Service Captain",
    company: "Zen Restaurant Kigali",
    companyColor: "#880E4F",
    companyInitials: "ZRK",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Restaurant",
    salary: "RWF 260,000 – 360,000 /mo",
    experience: "2+ years",
    posted: "5 days ago",
    deadline: "May 16, 2026",
    urgent: false,
    featured: false,
    views: 874,
    applicants: 67,
    description:
      "Lead service on the floor, manage table stations, mentor junior waitstaff, and ensure every guest leaves with an exceptional dining memory at this popular Asian fusion restaurant.",
    requirements: [
      "Fine dining silver service experience",
      "Working knowledge of Asian cuisine and dining etiquette",
      "Strong communication and English language skills",
      "Calm, professional demeanour under pressure",
    ],
    skills: ["Silver Service", "Table Management", "Asian Cuisine", "Team Mentoring", "Upselling"],
    logo: "🥢",
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&h=350&fit=crop",
  },
  {
    id: 19,
    title: "Mixologist / Bar Manager",
    company: "Chic Bar & Lounge",
    companyColor: "#6A1B9A",
    companyInitials: "CBL",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Bar",
    salary: "RWF 400,000 – 560,000 /mo",
    experience: "3+ years",
    posted: "1 day ago",
    deadline: "May 8, 2026",
    urgent: true,
    featured: false,
    views: 1768,
    applicants: 82,
    description:
      "Craft signature cocktails, manage bar inventory and lead a team of bartenders for Kigali's trendiest lounge. Drive promotional cocktail events and create Instagram-worthy drinks that draw an upscale crowd.",
    requirements: [
      "Mixology certification or equivalent proven experience",
      "Beverage cost management and inventory control",
      "Experience managing a high-volume bar",
      "Creative flair and exceptional presentation skills",
    ],
    skills: ["Cocktail Creation", "Bar Management", "Beverage Cost", "Social Media Content", "Team Leadership"],
    logo: "🍹",
    image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=600&h=350&fit=crop",
  },
  {
    id: 20,
    title: "Hotel Sales Manager",
    company: "Lemigo Hotel",
    companyColor: "#004D40",
    companyInitials: "LH",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 700,000 – 1,000,000 /mo",
    experience: "5+ years",
    posted: "1 week ago",
    deadline: "Jun 3, 2026",
    urgent: false,
    featured: false,
    views: 1098,
    applicants: 36,
    description:
      "Drive corporate and MICE (Meetings, Incentives, Conferences, Exhibitions) sales for a leading Kigali business hotel. Build and maintain relationships with embassies, NGOs, government agencies, and corporates.",
    requirements: [
      "Hotel sales or business development background (5+ years)",
      "Corporate account management experience",
      "Excellent negotiation and contract skills",
      "Bilingual English/French strongly preferred",
    ],
    skills: ["B2B Sales", "MICE", "Contract Negotiation", "CRM", "French"],
    logo: "💼",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=350&fit=crop",
  },
  {
    id: 21,
    title: "Commis Chef – Grill Section",
    company: "Karibu Restaurant",
    companyColor: "#E65100",
    companyInitials: "KR",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Restaurant",
    salary: "RWF 180,000 – 250,000 /mo",
    experience: "Fresh graduate / 1 year",
    posted: "3 days ago",
    deadline: "May 13, 2026",
    urgent: false,
    featured: false,
    views: 2210,
    applicants: 118,
    description:
      "Join a vibrant restaurant kitchen in the grill section. Learn from senior chefs, maintain station cleanliness, prep ingredients, and assist in cooking meat and fish dishes to order.",
    requirements: [
      "Culinary school graduate preferred",
      "Genuine passion for cooking and the kitchen environment",
      "Available for split shifts (morning and evening)",
      "Strong team player with a positive attitude",
    ],
    skills: ["Grill Cooking", "Prep Work", "Kitchen Hygiene", "Mise en Place", "Team Collaboration"],
    logo: "🔥",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=350&fit=crop",
  },
  {
    id: 22,
    title: "Concierge Supervisor",
    company: "Kigali Serena Hotel",
    companyColor: "#1565C0",
    companyInitials: "KSH",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 380,000 – 520,000 /mo",
    experience: "3+ years",
    posted: "8 days ago",
    deadline: "May 27, 2026",
    urgent: false,
    featured: false,
    views: 780,
    applicants: 43,
    description:
      "Lead the concierge team in delivering unparalleled guest assistance. Handle VIP itineraries, restaurant reservations, transportation and bespoke experiences for a highly international guest base.",
    requirements: [
      "Concierge or front office background (3+ years)",
      "Extensive knowledge of Kigali and Rwanda",
      "Excellent interpersonal and communication skills",
      "Multi-lingual: English + French essential; Italian or German a bonus",
    ],
    skills: ["Concierge Services", "VIP Hosting", "Local Knowledge", "French", "Luxury Standards"],
    logo: "🔑",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=600&h=350&fit=crop",
  },
  {
    id: 23,
    title: "Pool & Beach Butler",
    company: "Kivu Sun Hotel",
    companyColor: "#0277BD",
    companyInitials: "KSH",
    location: "Gisenyi, Western Province",
    province: "Western",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 220,000 – 310,000 /mo",
    experience: "1+ year",
    posted: "2 days ago",
    deadline: "May 11, 2026",
    urgent: false,
    featured: false,
    views: 943,
    applicants: 77,
    description:
      "Provide exceptional poolside and lakefront service to guests at this iconic Lake Kivu resort. Manage towel service, beverage orders, pool area safety, and maintain the welcoming lakeside ambiance.",
    requirements: [
      "Hospitality or tourism background preferred",
      "Swimming proficiency and water safety knowledge",
      "Cheerful, proactive guest-oriented personality",
      "Available for weekends and public holidays",
    ],
    skills: ["Pool Service", "F&B Service", "Guest Experience", "Safety Awareness", "Upselling"],
    logo: "🏊",
    image: "https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=600&h=350&fit=crop",
  },
  {
    id: 24,
    title: "Marketing & Social Media Executive",
    company: "Akagera Game Lodge",
    companyColor: "#558B2F",
    companyInitials: "AGL",
    location: "Akagera, Eastern Province",
    province: "Eastern",
    type: "Full-time",
    category: "Lodge",
    salary: "RWF 350,000 – 500,000 /mo",
    experience: "2+ years",
    posted: "4 days ago",
    deadline: "May 19, 2026",
    urgent: true,
    featured: false,
    views: 1654,
    applicants: 94,
    description:
      "Create compelling digital content, manage social channels, and run campaigns for Rwanda's premier game lodge. Capture the magic of Akagera National Park through photography and videography to attract global travellers.",
    requirements: [
      "Digital marketing experience (2+ years)",
      "Photography and videography skills (Lightroom/Premiere/CapCut)",
      "Expert in Instagram, Facebook, TikTok and LinkedIn",
      "Genuine passion for wildlife and conservation storytelling",
    ],
    skills: ["Content Creation", "Instagram", "Photography", "Videography", "SEO"],
    logo: "📸",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600&h=350&fit=crop",
  },
  {
    id: 25,
    title: "Banquet & Events Supervisor",
    company: "Kigali Marriott Hotel",
    companyColor: "#C62828",
    companyInitials: "KMH",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 420,000 – 580,000 /mo",
    experience: "3+ years",
    posted: "5 days ago",
    deadline: "May 26, 2026",
    urgent: false,
    featured: false,
    views: 688,
    applicants: 39,
    description:
      "Supervise setup, service and breakdown for all banquets and private dining events. Coordinate seamlessly between kitchen, AV and operations teams to ensure flawless event execution for up to 1,000 delegates.",
    requirements: [
      "Banqueting or F&B supervisory experience (3+ years)",
      "Proven ability to lead event service teams under pressure",
      "Physical fitness for event setup and breakdown",
      "Flexible schedule including evenings and weekends",
    ],
    skills: ["Banquet Service", "Event Coordination", "Team Leadership", "AV Liaison", "Floor Planning"],
    logo: "🎊",
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&h=350&fit=crop",
  },
  {
    id: 26,
    title: "Steward / Kitchen Porter",
    company: "Muhima Lodge",
    companyColor: "#4E342E",
    companyInitials: "ML",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Lodge",
    salary: "RWF 130,000 – 190,000 /mo",
    experience: "No experience required",
    posted: "1 day ago",
    deadline: "May 9, 2026",
    urgent: true,
    featured: false,
    views: 1890,
    applicants: 156,
    description:
      "Support kitchen operations through dishwashing, equipment cleaning, waste management and supply deliveries. An entry-level position with genuine career growth into kitchen roles for the right candidate.",
    requirements: [
      "Willingness to work hard and learn",
      "Physical fitness for a standing, active role",
      "Reliable, punctual and team-oriented",
      "Positive attitude and eagerness to grow",
    ],
    skills: ["Kitchen Hygiene", "Equipment Cleaning", "Waste Management", "Stock Handling", "Teamwork"],
    logo: "🧹",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=350&fit=crop",
  },
  {
    id: 27,
    title: "Cocktail Waitress / Host",
    company: "Inzozi Bar & Terrace",
    companyColor: "#AD1457",
    companyInitials: "IBT",
    location: "Kigali City",
    province: "Kigali",
    type: "Part-time",
    category: "Bar",
    salary: "RWF 150,000 – 220,000 /mo",
    experience: "1+ year",
    posted: "3 days ago",
    deadline: "May 10, 2026",
    urgent: false,
    featured: false,
    views: 1423,
    applicants: 88,
    description:
      "Welcome and seat guests, take beverage orders, and maintain an energetic, welcoming atmosphere at this stylish rooftop bar. Evening and weekend shifts. Commissions on table sales.",
    requirements: [
      "Outgoing, confident and warm personality",
      "Basic knowledge of cocktails and beverages",
      "Smart, professional appearance",
      "Consistent weekend availability required",
    ],
    skills: ["Guest Hosting", "Beverage Knowledge", "Upselling", "POS Systems", "Customer Service"],
    logo: "🌙",
    image: "https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=600&h=350&fit=crop",
  },
  {
    id: 28,
    title: "Hotel Controller / Accountant",
    company: "Park Inn by Radisson, Kigali",
    companyColor: "#0D47A1",
    companyInitials: "PIR",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 750,000 – 1,050,000 /mo",
    experience: "5+ years",
    posted: "1 week ago",
    deadline: "Jun 2, 2026",
    urgent: false,
    featured: false,
    views: 682,
    applicants: 23,
    description:
      "Oversee the full financial cycle of a branded hotel: monthly reporting, cost control, audit liaison, payroll and statutory compliance. Work closely with the GM and regional finance team.",
    requirements: [
      "CPA or ACCA qualification required",
      "Hotel-specific accounting software (Sun, Opera Finance)",
      "Advanced Excel and financial modelling skills",
      "Hospitality industry experience strongly preferred",
    ],
    skills: ["CPA/ACCA", "Hotel Accounting", "Financial Reporting", "Cost Control", "Payroll"],
    logo: "🧾",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=350&fit=crop",
  },
  {
    id: 29,
    title: "Room Service Supervisor",
    company: "Gorilla's Nest Lodge",
    companyColor: "#2E7D32",
    companyInitials: "GNL",
    location: "Kinigi, Musanze",
    province: "Northern",
    type: "Full-time",
    category: "Lodge",
    salary: "RWF 280,000 – 380,000 /mo",
    experience: "2+ years",
    posted: "6 days ago",
    deadline: "May 23, 2026",
    urgent: false,
    featured: false,
    views: 534,
    applicants: 27,
    description:
      "Coordinate and supervise in-room dining service for lodge guests. Ensure timely delivery, correct order accuracy, and exceptional presentation for every room service experience at this ultra-luxury property.",
    requirements: [
      "F&B service background with room service experience",
      "Supervisory or team leader experience",
      "Attention to quality, timing and visual presentation",
      "Calm and efficient under pressure",
    ],
    skills: ["Room Service", "F&B Supervision", "Order Accuracy", "Guest Liaison", "Quality Control"],
    logo: "🍱",
    image: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=600&h=350&fit=crop",
  },
  {
    id: 30,
    title: "Barback & Bar Trainee",
    company: "Bourbon Coffee & Bar",
    companyColor: "#5D4037",
    companyInitials: "BCB",
    location: "Kigali City",
    province: "Kigali",
    type: "Internship",
    category: "Bar",
    salary: "RWF 100,000 – 150,000 /mo",
    experience: "No experience required",
    posted: "2 days ago",
    deadline: "May 12, 2026",
    urgent: false,
    featured: false,
    views: 3104,
    applicants: 201,
    description:
      "Join our bar team as a paid trainee. Learn from experienced bartenders, maintain bar stock, assist in cocktail preparation, and develop the skills to become a fully-fledged bartender within 6 months.",
    requirements: [
      "Genuine passion for the drinks and hospitality industry",
      "Eager to learn and take direction from senior staff",
      "Must be aged 18 or over",
      "Available for flexible shifts including weekends",
    ],
    skills: ["Bar Setup", "Stock Rotation", "Cocktail Prep", "Customer Interaction", "Teamwork"],
    logo: "🎓",
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&h=350&fit=crop",
  },
  {
    id: 31,
    title: "Executive Housekeeper",
    company: "Kigali Heights Hotel",
    companyColor: "#37474F",
    companyInitials: "KHH",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 650,000 – 900,000 /mo",
    experience: "6+ years",
    posted: "4 days ago",
    deadline: "May 24, 2026",
    urgent: true,
    featured: false,
    views: 891,
    applicants: 33,
    description:
      "Lead the entire housekeeping department including rooms, public areas, laundry and linen. Set brand standards, manage a team of 35+ housekeeping staff, and control the full departmental budget.",
    requirements: [
      "Executive Housekeeper or Head Housekeeper experience",
      "Proven leadership of large departmental teams (30+)",
      "Budget planning and cost control experience",
      "Knowledge of luxury hotel brand standards",
    ],
    skills: ["Department Leadership", "Budget Control", "Brand Standards", "Linen Management", "Quality Audits"],
    logo: "🏨",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&h=350&fit=crop",
  },
  {
    id: 32,
    title: "Head of Catering",
    company: "Rwanda Culinary Arts Centre",
    companyColor: "#BF360C",
    companyInitials: "RCAC",
    location: "Kigali City",
    province: "Kigali",
    type: "Full-time",
    category: "Restaurant",
    salary: "RWF 700,000 – 950,000 /mo",
    experience: "6+ years",
    posted: "1 week ago",
    deadline: "Jun 7, 2026",
    urgent: false,
    featured: false,
    views: 788,
    applicants: 29,
    description:
      "Lead the catering department supplying corporate clients, NGOs, embassies and government functions across Kigali. Manage production planning, cost control and a kitchen team of 20.",
    requirements: [
      "Catering management experience (6+ years)",
      "Large-scale food production and logistics knowledge",
      "HACCP Level 3 and food safety certification",
      "Strong budget and cost-control skills",
    ],
    skills: ["Large-Scale Catering", "Production Planning", "HACCP Level 3", "Cost Control", "Client Relations"],
    logo: "🍽️",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=350&fit=crop",
  },
];

export const categories = ["All", "Hotel", "Restaurant", "Bar", "Lodge", "Lounge"];
export const jobTypes = ["All Types", "Full-time", "Part-time", "Contract", "Internship"];
export const provinces = ["All Provinces", "Kigali", "Northern", "Western", "Eastern", "Southern"];

export const stats = [
  { value: "500+", label: "Jobs Placed" },
  { value: "200+", label: "Partner Businesses" },
  { value: "98%", label: "Client Satisfaction" },
  { value: "5", label: "Provinces Covered" },
];
