export interface Job {
  id: number;
  title: string;
  company: string;
  location: string;
  type: string;
  category: string;
  salary: string;
  experience: string;
  posted: string;
  urgent: boolean;
  description: string;
  requirements: string[];
  logo: string;
  /** Unsplash image URL (free/open) */
  image: string;
}

export const jobs: Job[] = [
  // ── HOTELS ──────────────────────────────────────────────────────────────
  {
    id: 1,
    title: "Executive Chef",
    company: "Kigali Serena Hotel",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 800,000 – 1,200,000 /mo",
    experience: "5+ years",
    posted: "2 days ago",
    urgent: true,
    description:
      "Lead the culinary team at one of Kigali's premier luxury hotels. Oversee kitchen operations, menu creation, and ensure exceptional dining experiences across all outlets.",
    requirements: [
      "Culinary degree or equivalent",
      "5+ years in a senior kitchen role",
      "Experience with international cuisine",
      "Strong leadership and team management",
    ],
    logo: "🏨",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=250&fit=crop",
  },
  {
    id: 2,
    title: "Front Desk Manager",
    company: "Gorilla's Nest Lodge",
    location: "Kinigi, Musanze",
    type: "Full-time",
    category: "Lodge",
    salary: "RWF 450,000 – 600,000 /mo",
    experience: "3+ years",
    posted: "1 week ago",
    urgent: false,
    description:
      "Manage front office operations for an eco-luxury lodge near Volcanoes National Park. Supervise guest check-in/out, reservations, and concierge services.",
    requirements: [
      "Hospitality management degree",
      "Fluent in English and French",
      "Experience with PMS software",
      "Excellent customer service skills",
    ],
    logo: "🌿",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=250&fit=crop",
  },
  {
    id: 3,
    title: "Head Bartender",
    company: "Sky Bar Kigali",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Bar",
    salary: "RWF 350,000 – 500,000 /mo",
    experience: "3+ years",
    posted: "3 days ago",
    urgent: true,
    description:
      "Create and manage cocktail menus for Kigali's most iconic rooftop bar. Train junior staff and ensure top-tier beverage service standards.",
    requirements: [
      "Advanced bartending certification",
      "Creative mixology skills",
      "Knowledge of wines and spirits",
      "Evening/weekend availability",
    ],
    logo: "🍸",
    image: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=400&h=250&fit=crop",
  },
  {
    id: 4,
    title: "Restaurant Manager",
    company: "Repub Lounge",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Restaurant",
    salary: "RWF 500,000 – 700,000 /mo",
    experience: "4+ years",
    posted: "5 days ago",
    urgent: false,
    description:
      "Oversee daily restaurant operations, manage staff scheduling, ensure quality standards, and drive revenue growth for one of Kigali's most beloved dining spots.",
    requirements: [
      "Restaurant management experience",
      "Financial acumen & budgeting",
      "Team leadership skills",
      "Food safety certification",
    ],
    logo: "🍽️",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=250&fit=crop",
  },
  {
    id: 5,
    title: "Guest Relations Officer",
    company: "One&Only Nyungwe House",
    location: "Nyamasheke, Western Province",
    type: "Full-time",
    category: "Lodge",
    salary: "RWF 380,000 – 520,000 /mo",
    experience: "2+ years",
    posted: "1 day ago",
    urgent: false,
    description:
      "Deliver world-class guest experiences at an ultra-luxury lodge on the edge of Nyungwe Forest. Coordinate activities, transfers, and personalized itineraries.",
    requirements: [
      "Hospitality background",
      "Excellent communication skills",
      "Multi-lingual (English, French preferred)",
      "Passion for eco-tourism",
    ],
    logo: "🌲",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&h=250&fit=crop",
  },
  {
    id: 6,
    title: "Housekeeping Supervisor",
    company: "Marriott Hotel Kigali",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 320,000 – 420,000 /mo",
    experience: "2+ years",
    posted: "2 weeks ago",
    urgent: false,
    description:
      "Supervise housekeeping team to maintain Marriott brand standards across all rooms and public areas. Schedule staff, conduct inspections and manage supply inventory.",
    requirements: [
      "Housekeeping or hospitality diploma",
      "Supervisory experience",
      "Attention to detail",
      "Physical stamina",
    ],
    logo: "🏩",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=250&fit=crop",
  },
  {
    id: 7,
    title: "Sous Chef",
    company: "Heaven Restaurant & Boutique Hotel",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Restaurant",
    salary: "RWF 480,000 – 650,000 /mo",
    experience: "3+ years",
    posted: "4 days ago",
    urgent: true,
    description:
      "Support the Executive Chef in running the kitchen of a celebrated Kigali institution. Focus on Rwandan and fusion cuisine, staff training, and prep management.",
    requirements: [
      "Culinary training required",
      "Proficiency in African & international cuisines",
      "Team player with leadership potential",
      "HACCP knowledge",
    ],
    logo: "👨‍🍳",
    image: "https://images.unsplash.com/photo-1581349485608-9469926a8e5e?w=400&h=250&fit=crop",
  },
  {
    id: 8,
    title: "Barista & Coffee Specialist",
    company: "Bourbon Coffee",
    location: "Multiple Locations, Kigali",
    type: "Full-time",
    category: "Bar",
    salary: "RWF 200,000 – 320,000 /mo",
    experience: "1+ year",
    posted: "1 week ago",
    urgent: false,
    description:
      "Prepare exceptional Rwandan specialty coffee and educate customers on Rwanda's coffee heritage. Ideal for passionate baristas who love the story behind the cup.",
    requirements: [
      "Barista certification preferred",
      "Knowledge of coffee origins",
      "Customer-facing experience",
      "Positive attitude",
    ],
    logo: "☕",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=250&fit=crop",
  },
  {
    id: 9,
    title: "Events Coordinator",
    company: "Kigali Convention Centre",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Lounge",
    salary: "RWF 420,000 – 580,000 /mo",
    experience: "3+ years",
    posted: "6 days ago",
    urgent: false,
    description:
      "Plan and execute corporate events, conferences, and banquets at Rwanda's premier convention centre. Liaise with clients, vendors and AV teams.",
    requirements: [
      "Event management degree/diploma",
      "Project management skills",
      "Vendor negotiation experience",
      "Bilingual (English/French)",
    ],
    logo: "🎪",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=250&fit=crop",
  },
  // ── NEW JOBS ─────────────────────────────────────────────────────────────
  {
    id: 10,
    title: "Hotel General Manager",
    company: "Radisson Blu Kigali",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 2,000,000 – 3,500,000 /mo",
    experience: "10+ years",
    posted: "3 days ago",
    urgent: true,
    description:
      "Lead all aspects of hotel operations at the newly expanded Radisson Blu Kigali. P&L accountability, team development, and representing the brand at the highest level.",
    requirements: [
      "Hotel management degree",
      "10+ years luxury hotel experience",
      "Proven P&L management",
      "International brand standard knowledge",
    ],
    logo: "🏦",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400&h=250&fit=crop",
  },
  {
    id: 11,
    title: "Pastry Chef",
    company: "Kigali Marriott Hotel",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 550,000 – 750,000 /mo",
    experience: "4+ years",
    posted: "5 days ago",
    urgent: false,
    description:
      "Design and execute the pastry and bakery menu for all F&B outlets. Create showpiece desserts for events and ensure consistency in quality and presentation.",
    requirements: [
      "Pastry arts degree or equivalent",
      "Advanced chocolate & sugar work skills",
      "Experience in luxury hotel settings",
      "Creativity and attention to detail",
    ],
    logo: "🧁",
    image: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=400&h=250&fit=crop",
  },
  {
    id: 12,
    title: "Spa & Wellness Manager",
    company: "Lake Kivu Serena Hotel",
    location: "Gisenyi, Western Province",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 600,000 – 850,000 /mo",
    experience: "4+ years",
    posted: "1 week ago",
    urgent: false,
    description:
      "Oversee the spa, fitness centre, and wellness programmes at this lakeside luxury retreat. Manage therapists, develop treatment menus, and drive spa revenue.",
    requirements: [
      "Spa management certification",
      "Knowledge of wellness therapies",
      "Team leadership experience",
      "Revenue management skills",
    ],
    logo: "💆",
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&h=250&fit=crop",
  },
  {
    id: 13,
    title: "Food & Beverage Director",
    company: "Kigali Heights Hotel",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 1,200,000 – 1,800,000 /mo",
    experience: "7+ years",
    posted: "2 days ago",
    urgent: true,
    description:
      "Direct all F&B operations across multiple outlets including restaurants, bars, room service and banqueting. Drive profit, menu innovation and guest satisfaction scores.",
    requirements: [
      "F&B Director level experience",
      "Strong financial management",
      "Menu engineering expertise",
      "Multi-outlet management",
    ],
    logo: "🍷",
    image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=400&h=250&fit=crop",
  },
  {
    id: 14,
    title: "Sommelier",
    company: "The Manor Hotel Kigali",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Restaurant",
    salary: "RWF 480,000 – 650,000 /mo",
    experience: "3+ years",
    posted: "4 days ago",
    urgent: false,
    description:
      "Curate and manage an exceptional wine cellar and beverage programme. Lead wine pairing dinners and staff training sessions for one of Kigali's upscale dining venues.",
    requirements: [
      "WSET Level 3 or Court of Master Sommeliers",
      "Extensive wine knowledge",
      "Training and presentation skills",
      "Passion for hospitality",
    ],
    logo: "🍾",
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=250&fit=crop",
  },
  {
    id: 15,
    title: "Lodge Guide & Safari Coordinator",
    company: "Sabyinyo Silverback Lodge",
    location: "Musanze, Northern Province",
    type: "Full-time",
    category: "Lodge",
    salary: "RWF 350,000 – 500,000 /mo",
    experience: "2+ years",
    posted: "3 days ago",
    urgent: false,
    description:
      "Lead gorilla trekking excursions, nature walks and cultural tours for guests at this award-winning lodge. Ensure safety, provide expertise and create memorable wildlife experiences.",
    requirements: [
      "RDB-certified guide licence",
      "Deep knowledge of Rwandan flora & fauna",
      "First aid certification",
      "Fluent English; French a plus",
    ],
    logo: "🦍",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=400&h=250&fit=crop",
  },
  {
    id: 16,
    title: "Reservations & Revenue Manager",
    company: "Bisate Lodge",
    location: "Kinigi, Musanze",
    type: "Full-time",
    category: "Lodge",
    salary: "RWF 550,000 – 750,000 /mo",
    experience: "3+ years",
    posted: "6 days ago",
    urgent: false,
    description:
      "Manage all booking channels, pricing strategy, and occupancy optimisation for this high-end eco-lodge. Interface with global tour operators and OTAs.",
    requirements: [
      "Revenue management experience",
      "Knowledge of channel management systems",
      "Strong analytical skills",
      "Eco-luxury hospitality background",
    ],
    logo: "📊",
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764bef?w=400&h=250&fit=crop",
  },
  {
    id: 17,
    title: "Night Auditor",
    company: "Park Inn by Radisson",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 250,000 – 340,000 /mo",
    experience: "1+ year",
    posted: "2 weeks ago",
    urgent: false,
    description:
      "Manage overnight front desk operations and reconcile daily financials. Assist late-arriving guests and prepare morning management reports.",
    requirements: [
      "Accounting or hospitality background",
      "Proficiency with Opera PMS",
      "Night shift availability",
      "Attention to detail",
    ],
    logo: "🌙",
    image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=400&h=250&fit=crop",
  },
  {
    id: 18,
    title: "Senior Waiter / Service Captain",
    company: "Zen Restaurant Kigali",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Restaurant",
    salary: "RWF 260,000 – 360,000 /mo",
    experience: "2+ years",
    posted: "5 days ago",
    urgent: false,
    description:
      "Lead service on the floor, manage table stations, mentor junior waitstaff, and ensure every guest leaves with an exceptional dining memory at this Asian fusion restaurant.",
    requirements: [
      "Fine dining service experience",
      "Knowledge of Asian cuisine & etiquette",
      "Strong communication skills",
      "Calm under pressure",
    ],
    logo: "🥢",
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=250&fit=crop",
  },
  {
    id: 19,
    title: "Mixologist / Bar Manager",
    company: "Chic Bar & Lounge",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Bar",
    salary: "RWF 400,000 – 560,000 /mo",
    experience: "3+ years",
    posted: "1 day ago",
    urgent: true,
    description:
      "Craft signature cocktails, manage bar inventory, and lead a team of bartenders for Kigali's trendiest lounge. Drive promotional cocktail events and social-media-worthy drinks.",
    requirements: [
      "Mixology certification or equivalent",
      "Beverage cost management",
      "Experience in a high-volume bar",
      "Creative flair and presentation skills",
    ],
    logo: "🍹",
    image: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=400&h=250&fit=crop",
  },
  {
    id: 20,
    title: "Hotel Sales Manager",
    company: "Lemigo Hotel",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 700,000 – 1,000,000 /mo",
    experience: "5+ years",
    posted: "1 week ago",
    urgent: false,
    description:
      "Drive corporate and MICE (Meetings, Incentives, Conferences, Exhibitions) sales for a leading Kigali business hotel. Build relationships with embassies, NGOs, and corporates.",
    requirements: [
      "Hotel sales background",
      "Corporate account management experience",
      "Excellent negotiation skills",
      "Bilingual (English/French)",
    ],
    logo: "💼",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=250&fit=crop",
  },
  {
    id: 21,
    title: "Commis Chef – Grill Section",
    company: "Karibu Restaurant",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Restaurant",
    salary: "RWF 180,000 – 250,000 /mo",
    experience: "Fresh graduate / 1 year",
    posted: "3 days ago",
    urgent: false,
    description:
      "Join a vibrant restaurant kitchen in the grill section. Learn from senior chefs, maintain station cleanliness, prep ingredients, and assist in cooking meat and fish dishes.",
    requirements: [
      "Culinary school graduate preferred",
      "Passion for cooking",
      "Available for split shifts",
      "Team player",
    ],
    logo: "🔥",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=250&fit=crop",
  },
  {
    id: 22,
    title: "Concierge Supervisor",
    company: "Kigali Serena Hotel",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 380,000 – 520,000 /mo",
    experience: "3+ years",
    posted: "8 days ago",
    urgent: false,
    description:
      "Lead the concierge team in delivering unparalleled guest assistance. Handle VIP itineraries, restaurant reservations, transportation and bespoke experiences for international travellers.",
    requirements: [
      "Concierge or front office background",
      "Extensive knowledge of Kigali & Rwanda",
      "Excellent interpersonal skills",
      "Multi-lingual preferred",
    ],
    logo: "🔑",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=250&fit=crop",
  },
  {
    id: 23,
    title: "Pool & Beach Butler",
    company: "Kivu Sun Hotel",
    location: "Gisenyi, Western Province",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 220,000 – 310,000 /mo",
    experience: "1+ year",
    posted: "2 days ago",
    urgent: false,
    description:
      "Provide exceptional poolside and lakefront service to guests at this iconic Lake Kivu resort. Manage towel service, food and beverage orders, and ensure pool area safety.",
    requirements: [
      "Hospitality or tourism background",
      "Swimming proficiency",
      "Cheerful guest-oriented personality",
      "Available for weekends and holidays",
    ],
    logo: "🏊",
    image: "https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=400&h=250&fit=crop",
  },
  {
    id: 24,
    title: "Marketing & Social Media Executive",
    company: "Akagera Game Lodge",
    location: "Akagera, Eastern Province",
    type: "Full-time",
    category: "Lodge",
    salary: "RWF 350,000 – 500,000 /mo",
    experience: "2+ years",
    posted: "4 days ago",
    urgent: true,
    description:
      "Create compelling digital content, manage social channels, and run campaigns for Rwanda's premier game lodge. Capture the magic of Akagera National Park to attract global travellers.",
    requirements: [
      "Digital marketing experience",
      "Photography/videography skills",
      "Social media platform expertise",
      "Passion for wildlife & conservation",
    ],
    logo: "📸",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=400&h=250&fit=crop",
  },
  {
    id: 25,
    title: "Banquet & Events Supervisor",
    company: "Kigali Marriott Hotel",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 420,000 – 580,000 /mo",
    experience: "3+ years",
    posted: "5 days ago",
    urgent: false,
    description:
      "Supervise setup, service and breakdown for all banquets and private dining events. Coordinate between kitchen, AV and operations teams to deliver seamless events.",
    requirements: [
      "Banqueting or F&B supervisory experience",
      "Ability to lead event teams",
      "Physical fitness for event setup",
      "Flexible schedule including weekends",
    ],
    logo: "🎊",
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400&h=250&fit=crop",
  },
  {
    id: 26,
    title: "Steward / Kitchen Porter",
    company: "Muhima Lodge",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Lodge",
    salary: "RWF 130,000 – 190,000 /mo",
    experience: "No experience required",
    posted: "1 day ago",
    urgent: true,
    description:
      "Support kitchen operations through dishwashing, equipment cleaning, waste management, and deliveries. Entry-level role with strong potential for career growth.",
    requirements: [
      "Willingness to work hard",
      "Physical fitness",
      "Reliable and punctual",
      "Positive team attitude",
    ],
    logo: "🧹",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=250&fit=crop",
  },
  {
    id: 27,
    title: "Cocktail Waitress / Host",
    company: "Inzozi Bar & Terrace",
    location: "Kigali, Rwanda",
    type: "Part-time",
    category: "Bar",
    salary: "RWF 150,000 – 220,000 /mo",
    experience: "1+ year",
    posted: "3 days ago",
    urgent: false,
    description:
      "Welcome and seat guests, take beverage orders, and ensure an energetic, welcoming atmosphere at this stylish rooftop bar. Evening and weekend shifts primarily.",
    requirements: [
      "Outgoing and confident personality",
      "Basic knowledge of beverages",
      "Smart appearance",
      "Weekend availability",
    ],
    logo: "🌙",
    image: "https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=400&h=250&fit=crop",
  },
  {
    id: 28,
    title: "Hotel Controller / Accountant",
    company: "Park Inn by Radisson, Kigali",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 750,000 – 1,050,000 /mo",
    experience: "5+ years",
    posted: "1 week ago",
    urgent: false,
    description:
      "Oversee the full financial cycle of a branded hotel: monthly reporting, cost control, audit liaison, payroll, and compliance. Work closely with the GM and corporate finance.",
    requirements: [
      "CPA or ACCA qualification",
      "Hotel accounting software proficiency",
      "Strong Excel and financial reporting",
      "Hospitality industry experience preferred",
    ],
    logo: "🧾",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=250&fit=crop",
  },
  {
    id: 29,
    title: "Room Service Supervisor",
    company: "Gorilla's Nest Lodge",
    location: "Kinigi, Musanze",
    type: "Full-time",
    category: "Lodge",
    salary: "RWF 280,000 – 380,000 /mo",
    experience: "2+ years",
    posted: "6 days ago",
    urgent: false,
    description:
      "Coordinate and supervise in-room dining service for lodge guests. Ensure timely delivery, correct order accuracy, and exceptional presentation for every room service experience.",
    requirements: [
      "F&B service background",
      "Supervisory experience",
      "Attention to quality and presentation",
      "Calm and efficient under pressure",
    ],
    logo: "🍱",
    image: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=400&h=250&fit=crop",
  },
  {
    id: 30,
    title: "Barback & Bar Trainee",
    company: "Bourbon Coffee & Bar",
    location: "Kigali, Rwanda",
    type: "Internship",
    category: "Bar",
    salary: "RWF 100,000 – 150,000 /mo",
    experience: "No experience required",
    posted: "2 days ago",
    urgent: false,
    description:
      "Join our bar team as a trainee. Learn from experienced bartenders, maintain bar stock, assist in cocktail preparation, and develop the skills to become a fully-fledged bartender.",
    requirements: [
      "Passion for drinks and hospitality",
      "Willingness to learn",
      "Aged 18+",
      "Available for flexible shifts",
    ],
    logo: "🎓",
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=400&h=250&fit=crop",
  },
  {
    id: 31,
    title: "Executive Housekeeper",
    company: "Kigali Heights Hotel",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Hotel",
    salary: "RWF 650,000 – 900,000 /mo",
    experience: "6+ years",
    posted: "4 days ago",
    urgent: true,
    description:
      "Lead the entire housekeeping department including rooms, public areas, laundry and linen. Set brand standards, manage a team of 30+, and control departmental costs.",
    requirements: [
      "Executive Housekeeper experience",
      "Team leadership of large teams",
      "Budget management",
      "Luxury hotel brand knowledge",
    ],
    logo: "🏨",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=250&fit=crop",
  },
  {
    id: 32,
    title: "Head of Catering",
    company: "Rwanda Culinary Arts Centre",
    location: "Kigali, Rwanda",
    type: "Full-time",
    category: "Restaurant",
    salary: "RWF 700,000 – 950,000 /mo",
    experience: "6+ years",
    posted: "1 week ago",
    urgent: false,
    description:
      "Lead the catering department supplying corporate clients, NGOs, embassies, and government functions. Manage production planning, cost control, and team of 20 kitchen staff.",
    requirements: [
      "Catering management experience",
      "Large-scale food production knowledge",
      "HACCP and food safety certification",
      "Budget and cost control skills",
    ],
    logo: "🍽️",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=250&fit=crop",
  },
];

export const categories = ["All", "Hotel", "Restaurant", "Bar", "Lodge", "Lounge"];
export const jobTypes = ["All Types", "Full-time", "Part-time", "Contract", "Internship"];

export const stats = [
  { value: "500+", label: "Jobs Placed" },
  { value: "200+", label: "Partner Businesses" },
  { value: "98%", label: "Client Satisfaction" },
  { value: "5", label: "Provinces Covered" },
];
